### ISSUE TITLE
E216: No such group or event: QuitPre * call OnExit()

### ISSUE THREAD

**Issue by zassen** [c-wind/supersearch#2]
启动vim的时候碰到如下error，插件的功能似乎也都不正常。
之前是通过bundle安装的supersearch.vim
E216: No such group or event: QuitPre \* call OnExit()

**Comment by c-wind** [comment]
嗯,这个应该是vim版本的事,我之前在mac上也出现,我回去确认下啊,或者你修改了提上来也行

**Comment by c-wind** [comment]
我改了下,你再试试
